#############################################################################
# Makefile for building: sc-machine
# Generated by qmake (2.01a) (Qt 4.8.3) on: ?? ???. 15 14:03:47 2013
# Project:  sc-machine.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile sc-machine.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-sc-memory \
		sub-sc-memory-test \
		sub-tools-sc-store-visual

sc-memory//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) sc-memory/ || $(MKDIR) sc-memory/ 
	cd sc-memory/ && $(QMAKE) /home/daniel/OSTIS/sc-machine/sc-memory/sc-memory.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o $(MAKEFILE)
sub-sc-memory-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) sc-memory/ || $(MKDIR) sc-memory/ 
	cd sc-memory/ && $(QMAKE) /home/daniel/OSTIS/sc-machine/sc-memory/sc-memory.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o $(MAKEFILE)
sub-sc-memory: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE)
sub-sc-memory-make_default-ordered: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) 
sub-sc-memory-make_default: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) 
sub-sc-memory-make_first-ordered: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) first
sub-sc-memory-make_first: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) first
sub-sc-memory-all-ordered: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) all
sub-sc-memory-all: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) all
sub-sc-memory-clean-ordered: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) clean
sub-sc-memory-clean: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) clean
sub-sc-memory-distclean-ordered: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) distclean
sub-sc-memory-distclean: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) distclean
sub-sc-memory-install_subtargets-ordered: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) install
sub-sc-memory-install_subtargets: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) install
sub-sc-memory-uninstall_subtargets-ordered: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-sc-memory-uninstall_subtargets: sc-memory//$(MAKEFILE) FORCE
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) uninstall
sc-memory/test//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) sc-memory/test/ || $(MKDIR) sc-memory/test/ 
	cd sc-memory/test/ && $(QMAKE) /home/daniel/OSTIS/sc-machine/sc-memory/test/test.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o $(MAKEFILE)
sub-sc-memory-test-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) sc-memory/test/ || $(MKDIR) sc-memory/test/ 
	cd sc-memory/test/ && $(QMAKE) /home/daniel/OSTIS/sc-machine/sc-memory/test/test.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o $(MAKEFILE)
sub-sc-memory-test: sc-memory/test//$(MAKEFILE) FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE)
sub-sc-memory-test-make_default-ordered: sc-memory/test//$(MAKEFILE) sub-sc-memory-make_default-ordered  FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) 
sub-sc-memory-test-make_default: sc-memory/test//$(MAKEFILE) FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) 
sub-sc-memory-test-make_first-ordered: sc-memory/test//$(MAKEFILE) sub-sc-memory-make_first-ordered  FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) first
sub-sc-memory-test-make_first: sc-memory/test//$(MAKEFILE) FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) first
sub-sc-memory-test-all-ordered: sc-memory/test//$(MAKEFILE) sub-sc-memory-all-ordered  FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) all
sub-sc-memory-test-all: sc-memory/test//$(MAKEFILE) FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) all
sub-sc-memory-test-clean-ordered: sc-memory/test//$(MAKEFILE) sub-sc-memory-clean-ordered  FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) clean
sub-sc-memory-test-clean: sc-memory/test//$(MAKEFILE) FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) clean
sub-sc-memory-test-distclean-ordered: sc-memory/test//$(MAKEFILE) sub-sc-memory-distclean-ordered  FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) distclean
sub-sc-memory-test-distclean: sc-memory/test//$(MAKEFILE) FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) distclean
sub-sc-memory-test-install_subtargets-ordered: sc-memory/test//$(MAKEFILE) sub-sc-memory-install_subtargets-ordered  FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) install
sub-sc-memory-test-install_subtargets: sc-memory/test//$(MAKEFILE) FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) install
sub-sc-memory-test-uninstall_subtargets-ordered: sc-memory/test//$(MAKEFILE) sub-sc-memory-uninstall_subtargets-ordered  FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-sc-memory-test-uninstall_subtargets: sc-memory/test//$(MAKEFILE) FORCE
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) uninstall
tools/sc-store-visual//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tools/sc-store-visual/ || $(MKDIR) tools/sc-store-visual/ 
	cd tools/sc-store-visual/ && $(QMAKE) /home/daniel/OSTIS/sc-machine/tools/sc-store-visual/sc-store-visual.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o $(MAKEFILE)
sub-tools-sc-store-visual-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tools/sc-store-visual/ || $(MKDIR) tools/sc-store-visual/ 
	cd tools/sc-store-visual/ && $(QMAKE) /home/daniel/OSTIS/sc-machine/tools/sc-store-visual/sc-store-visual.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o $(MAKEFILE)
sub-tools-sc-store-visual: tools/sc-store-visual//$(MAKEFILE) FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE)
sub-tools-sc-store-visual-make_default-ordered: tools/sc-store-visual//$(MAKEFILE) sub-sc-memory-test-make_default-ordered  FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) 
sub-tools-sc-store-visual-make_default: tools/sc-store-visual//$(MAKEFILE) FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) 
sub-tools-sc-store-visual-make_first-ordered: tools/sc-store-visual//$(MAKEFILE) sub-sc-memory-test-make_first-ordered  FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) first
sub-tools-sc-store-visual-make_first: tools/sc-store-visual//$(MAKEFILE) FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) first
sub-tools-sc-store-visual-all-ordered: tools/sc-store-visual//$(MAKEFILE) sub-sc-memory-test-all-ordered  FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) all
sub-tools-sc-store-visual-all: tools/sc-store-visual//$(MAKEFILE) FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) all
sub-tools-sc-store-visual-clean-ordered: tools/sc-store-visual//$(MAKEFILE) sub-sc-memory-test-clean-ordered  FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) clean
sub-tools-sc-store-visual-clean: tools/sc-store-visual//$(MAKEFILE) FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) clean
sub-tools-sc-store-visual-distclean-ordered: tools/sc-store-visual//$(MAKEFILE) sub-sc-memory-test-distclean-ordered  FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) distclean
sub-tools-sc-store-visual-distclean: tools/sc-store-visual//$(MAKEFILE) FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) distclean
sub-tools-sc-store-visual-install_subtargets-ordered: tools/sc-store-visual//$(MAKEFILE) sub-sc-memory-test-install_subtargets-ordered  FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) install
sub-tools-sc-store-visual-install_subtargets: tools/sc-store-visual//$(MAKEFILE) FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) install
sub-tools-sc-store-visual-uninstall_subtargets-ordered: tools/sc-store-visual//$(MAKEFILE) sub-sc-memory-test-uninstall_subtargets-ordered  FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-tools-sc-store-visual-uninstall_subtargets: tools/sc-store-visual//$(MAKEFILE) FORCE
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: sc-machine.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile sc-machine.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile sc-machine.pro

qmake_all: sub-sc-memory-qmake_all sub-sc-memory-test-qmake_all sub-tools-sc-store-visual-qmake_all FORCE

make_default: sub-sc-memory-make_default-ordered sub-sc-memory-test-make_default-ordered sub-tools-sc-store-visual-make_default-ordered FORCE
make_first: sub-sc-memory-make_first-ordered sub-sc-memory-test-make_first-ordered sub-tools-sc-store-visual-make_first-ordered FORCE
all: sub-sc-memory-all-ordered sub-sc-memory-test-all-ordered sub-tools-sc-store-visual-all-ordered FORCE
clean: sub-sc-memory-clean-ordered sub-sc-memory-test-clean-ordered sub-tools-sc-store-visual-clean-ordered FORCE
distclean: sub-sc-memory-distclean-ordered sub-sc-memory-test-distclean-ordered sub-tools-sc-store-visual-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-sc-memory-install_subtargets-ordered sub-sc-memory-test-install_subtargets-ordered sub-tools-sc-store-visual-install_subtargets-ordered FORCE
uninstall_subtargets: sub-sc-memory-uninstall_subtargets-ordered sub-sc-memory-test-uninstall_subtargets-ordered sub-tools-sc-store-visual-uninstall_subtargets-ordered FORCE

sub-sc-memory-check_ordered: sc-memory/$(MAKEFILE)
	cd sc-memory/ && $(MAKE) -f $(MAKEFILE) check
sub-sc-memory-test-check_ordered: sc-memory/test/$(MAKEFILE) sub-sc-memory-check_ordered 
	cd sc-memory/test/ && $(MAKE) -f $(MAKEFILE) check
sub-tools-sc-store-visual-check_ordered: tools/sc-store-visual/$(MAKEFILE) sub-sc-memory-test-check_ordered 
	cd tools/sc-store-visual/ && $(MAKE) -f $(MAKEFILE) check
check: sub-sc-memory-check_ordered sub-sc-memory-test-check_ordered sub-tools-sc-store-visual-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

